insert into destinations (name, description, created_at, updated_at)
values ('Paris, France',
        'The romantic capital with iconic landmarks',
        now(),
        now()),
    ('Rome, Italy',
     'Ancient history and timeless architecture',
     now(),
     now()),
    ('Barcelona, Spain',
     'Mediterranean beaches and modernist masterpieces',
     now(),
     now()),
    ('Tokyo, Japan',
     'Where tradition meets cutting-edge modernity',
     now(),
     now()),
    ('Santorini, Greece',
     'Whitewashed villages and Aegean sunsets',
     now(),
     now()),
    ('Reykjavik, Iceland',
     'Volcanoes, glaciers, and the northern lights',
     now(),
     now()),
    ('Cairo, Egypt',
     'Pyramids, pharaohs, and the river Nile',
     now(),
     now()),
    ('New York, USA',
     'The city that never sleeps',
     now(),
     now()),
    ('Bali, Indonesia',
     'Tropical beaches and lush rice terraces',
     now(),
     now()),
    ('Cape Town, South Africa',
     'Where mountains meet two oceans',
     now(),
     now());

insert into tours (title, description, price, capacity, start_date, end_date, destination_id, created_at, updated_at)
values ('Paris City Highlights',
        'Explore the best of Paris on a guided city tour',
        49.99,
        50,
        '2026-06-01',
        '2026-08-01',
        (select id from destinations where name = 'Paris, France'),
        now(),
        now()),
    ('Ancient Rome Explorer',
     'Walk through the Colosseum, Forum, and Vatican',
     89.99,
     40,
     '2026-06-15',
     '2026-09-15',
     (select id from destinations where name = 'Rome, Italy'),
     now(),
     now()),
    ('Barcelona Beach and Gaudi',
     'Sun, sea, and stunning architecture',
     69.99,
     60,
     '2026-07-01',
     '2026-09-01',
     (select id from destinations where name = 'Barcelona, Spain'),
     now(),
     now()),
    ('Tokyo Discovery',
     'From ancient temples to neon skylines',
     99.99,
     35,
     '2026-07-10',
     '2026-10-10',
     (select id from destinations where name = 'Tokyo, Japan'),
     now(),
     now()),
    ('Santorini Island Escape',
     'Relax among whitewashed cliffs and sunsets',
     59.99,
     70,
     '2026-06-05',
     '2026-08-05',
     (select id from destinations where name = 'Santorini, Greece'),
     now(),
     now()),
    ('Iceland Northern Lights',
     'Chase auroras across volcanic landscapes',
     79.99,
     45,
     '2026-08-01',
     '2026-10-01',
     (select id from destinations where name = 'Reykjavik, Iceland'),
     now(),
     now()),
    ('Egypt Pyramids Adventure',
     'Discover the wonders of ancient Egypt',
     109.99,
     30,
     '2026-07-20',
     '2026-10-20',
     (select id from destinations where name = 'Cairo, Egypt'),
     now(),
     now()),
    ('New York City Break',
     'Experience the energy of the Big Apple',
     84.99,
     55,
     '2026-06-20',
     '2026-09-20',
     (select id from destinations where name = 'New York, USA'),
     now(),
     now()),
    ('Bali Tropical Retreat',
     'Beaches, temples, and emerald rice terraces',
     74.99,
     40,
     '2026-08-10',
     '2026-11-10',
     (select id from destinations where name = 'Bali, Indonesia'),
     now(),
     now()),
    ('Cape Town Coastal Tour',
     'Table Mountain and where two oceans meet',
     64.99,
     50,
     '2026-07-05',
     '2026-09-05',
     (select id from destinations where name = 'Cape Town, South Africa'),
     now(),
     now());
