insert into reservations (tour_id, user_id, created_at, updated_at)
values ((select id from tours where title = 'Paris City Highlights'),
        (select id from users where username = 'customer1'),
        now(),
        now()),
    ((select id from tours where title = 'Ancient Rome Explorer'),
     (select id from users where username = 'customer1'),
     now(),
     now()),
    ((select id from tours where title = 'Barcelona Beach and Gaudi'),
     (select id from users where username = 'customer1'),
     now(),
     now()),
    ((select id from tours where title = 'Paris City Highlights'),
     (select id from users where username = 'customer2'),
     now(),
     now()),
    ((select id from tours where title = 'Santorini Island Escape'),
     (select id from users where username = 'customer2'),
     now(),
     now()),
    ((select id from tours where title = 'Iceland Northern Lights'),
     (select id from users where username = 'customer2'),
     now(),
     now()),
    ((select id from tours where title = 'Tokyo Discovery'),
     (select id from users where username = 'customer3'),
     now(),
     now()),
    ((select id from tours where title = 'New York City Break'),
     (select id from users where username = 'customer3'),
     now(),
     now()),
    ((select id from tours where title = 'Bali Tropical Retreat'),
     (select id from users where username = 'customer3'),
     now(),
     now()),
    ((select id from tours where title = 'Cape Town Coastal Tour'),
     (select id from users where username = 'customer3'),
     now(),
     now());
