apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: travel-tours
data:
  DB_HOST: "travel-db"
  DB_PORT: "5432"
  DB_NAME: "travel_tours"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://travel-db.travel-tours.svc.cluster.local:5432/travel_tours"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"