apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: travel-tours
type: Opaque
stringData:
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  SPRING_DATASOURCE_USERNAME: "${DB_USER}"
  SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET_KEY: "${JWT_SECRET}"