apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: travel-db
  namespace: travel-tours
spec:
  serviceName: "travel-db"
  replicas: 1
  selector:
    matchLabels:
      app: travel-db
  template:
    metadata:
      labels:
        app: travel-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "travel_tours"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: travel-db
  namespace: travel-tours
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: travel-db
  clusterIP: None